// AUTO-GENERATED by scripts/generate-api-tests.ts — do not edit manually
// Write endpoints are skipped by default to avoid mutating live data.
// Enable individual tests in tests/api/manual/ for safe integration cases.
import { describe, it, expect } from "vitest";
import { createTestClient } from "../lib/testClient";
import { getAuthHeaders } from "../lib/auth";

describe("API integration tests (write endpoints)", () => {
  it.skip('POST /adjustments (services/adjustments.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.post('/adjustments', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('POST /auth/google/signin (services/auth.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.post('/auth/google/signin', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('POST /auth/google/signup (services/auth.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.post('/auth/google/signup', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('POST /auth/login (services/auth.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.post('/auth/login', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('PATCH /auth/reset (services/auth.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.patch('/auth/reset', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('POST /auth/reset (services/auth.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.post('/auth/reset', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('POST /auth/signup (services/auth.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.post('/auth/signup', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('POST /auth/validate-company (services/auth.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.post('/auth/validate-company', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('POST /auth/verify-account (services/auth.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.post('/auth/verify-account', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('POST /brands (services/brands.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.post('/brands', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('POST /business-users (services/business-users.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.post('/business-users', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('POST /business/onboard (services/business.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.post('/business/onboard', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('POST /categories (services/categories.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.post('/categories', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('POST /customers (services/customers.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.post('/customers', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('POST /expense-categories (services/expense-categories.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.post('/expense-categories', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('POST /expenses (services/expenses.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.post('/expenses', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('POST /products (services/products.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.post('/products', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('POST /purchases (services/purchases.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.post('/purchases', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('POST /purchases-return (services/purchase-returns.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.post('/purchases-return', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('POST /qoutations (services/quotations.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.post('/qoutations', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('POST /roles (services/roles.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.post('/roles', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('POST /sales (services/sales.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.post('/sales', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('POST /sales-return (services/sale-returns.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.post('/sales-return', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('POST /stores (services/stores.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.post('/stores', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('POST /suppliers (services/suppliers.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.post('/suppliers', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('POST /transfers (services/transfers.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.post('/transfers', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('POST /units (services/units.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.post('/units', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('POST /uploads/mulitple (services/upload.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.post('/uploads/mulitple', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('PUT /users/profile (services/users.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.put('/users/profile', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('POST /variations (services/variations.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.post('/variations', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('DELETE ${ENDPOINT.ADJUSTMENTS}/${id} (services/adjustments.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.delete('${ENDPOINT.ADJUSTMENTS}/${id}', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('PATCH ${ENDPOINT.ADJUSTMENTS}/${id} (services/adjustments.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.patch('${ENDPOINT.ADJUSTMENTS}/${id}', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('DELETE ${ENDPOINT.AUTH.ROLES}/${id} (services/roles.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.delete('${ENDPOINT.AUTH.ROLES}/${id}', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('PATCH ${ENDPOINT.AUTH.ROLES}/${id} (services/roles.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.patch('${ENDPOINT.AUTH.ROLES}/${id}', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('DELETE ${ENDPOINT.BRANDS}/${id} (services/brands.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.delete('${ENDPOINT.BRANDS}/${id}', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('PATCH ${ENDPOINT.BRANDS}/${id} (services/brands.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.patch('${ENDPOINT.BRANDS}/${id}', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('DELETE ${ENDPOINT.BUSINESS_USERS}/${id} (services/business-users.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.delete('${ENDPOINT.BUSINESS_USERS}/${id}', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('PATCH ${ENDPOINT.BUSINESS_USERS}/${id} (services/business-users.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.patch('${ENDPOINT.BUSINESS_USERS}/${id}', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('DELETE ${ENDPOINT.CATEGORIES}/${id} (services/categories.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.delete('${ENDPOINT.CATEGORIES}/${id}', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('PATCH ${ENDPOINT.CATEGORIES}/${id} (services/categories.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.patch('${ENDPOINT.CATEGORIES}/${id}', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('DELETE ${ENDPOINT.CUSTOMERS}/${id} (services/customers.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.delete('${ENDPOINT.CUSTOMERS}/${id}', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('PATCH ${ENDPOINT.CUSTOMERS}/${id} (services/customers.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.patch('${ENDPOINT.CUSTOMERS}/${id}', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('DELETE ${ENDPOINT.EXPENSE_CATEGORIES}/${id} (services/expense-categories.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.delete('${ENDPOINT.EXPENSE_CATEGORIES}/${id}', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('PATCH ${ENDPOINT.EXPENSE_CATEGORIES}/${id} (services/expense-categories.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.patch('${ENDPOINT.EXPENSE_CATEGORIES}/${id}', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('DELETE ${ENDPOINT.EXPENSES}/${id} (services/expenses.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.delete('${ENDPOINT.EXPENSES}/${id}', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('PATCH ${ENDPOINT.EXPENSES}/${id} (services/expenses.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.patch('${ENDPOINT.EXPENSES}/${id}', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('DELETE ${ENDPOINT.PRODUCTS}/${id} (services/products.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.delete('${ENDPOINT.PRODUCTS}/${id}', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('PATCH ${ENDPOINT.PRODUCTS}/${id} (services/products.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.patch('${ENDPOINT.PRODUCTS}/${id}', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('DELETE ${ENDPOINT.PURCHASES}/${id} (services/purchases.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.delete('${ENDPOINT.PURCHASES}/${id}', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('PATCH ${ENDPOINT.PURCHASES}/${id} (services/purchases.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.patch('${ENDPOINT.PURCHASES}/${id}', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('DELETE ${ENDPOINT.QUOTATIONS}/${id} (services/quotations.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.delete('${ENDPOINT.QUOTATIONS}/${id}', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('PATCH ${ENDPOINT.QUOTATIONS}/${id} (services/quotations.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.patch('${ENDPOINT.QUOTATIONS}/${id}', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('DELETE ${ENDPOINT.SALES}/${id} (services/sales.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.delete('${ENDPOINT.SALES}/${id}', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('PATCH ${ENDPOINT.SALES}/${id} (services/sales.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.patch('${ENDPOINT.SALES}/${id}', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('DELETE ${ENDPOINT.STORES.BASE}/${id} (services/stores.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.delete('${ENDPOINT.STORES.BASE}/${id}', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('PATCH ${ENDPOINT.STORES.BASE}/${id} (services/stores.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.patch('${ENDPOINT.STORES.BASE}/${id}', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('DELETE ${ENDPOINT.SUPPLIERS}/${id} (services/suppliers.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.delete('${ENDPOINT.SUPPLIERS}/${id}', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('PATCH ${ENDPOINT.SUPPLIERS}/${id} (services/suppliers.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.patch('${ENDPOINT.SUPPLIERS}/${id}', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('DELETE ${ENDPOINT.TRANSFERS}/${id} (services/transfers.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.delete('${ENDPOINT.TRANSFERS}/${id}', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('PATCH ${ENDPOINT.TRANSFERS}/${id} (services/transfers.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.patch('${ENDPOINT.TRANSFERS}/${id}', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('DELETE ${ENDPOINT.UNITS}/${id} (services/units.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.delete('${ENDPOINT.UNITS}/${id}', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('PATCH ${ENDPOINT.UNITS}/${id} (services/units.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.patch('${ENDPOINT.UNITS}/${id}', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('DELETE ${ENDPOINT.VARIATIONS}/${id} (services/variations.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.delete('${ENDPOINT.VARIATIONS}/${id}', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it.skip('PATCH ${ENDPOINT.VARIATIONS}/${id} (services/variations.ts)', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.patch('${ENDPOINT.VARIATIONS}/${id}', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });
});
