// AUTO-GENERATED by scripts/generate-api-tests.ts — do not edit manually
import { describe, it, expect, beforeAll } from "vitest";
import { createTestClient } from "../lib/testClient";
import { getAuthHeaders } from "../lib/auth";

describe("API smoke tests (GET)", () => {
  beforeAll(async () => {
    await getAuthHeaders();
  });

  it('GET /adjustments returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/adjustments');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /adjustments/summary/cards returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/adjustments/summary/cards');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /brands returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/brands');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /business-types returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/business-types');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /business-users returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/business-users');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /business/connect-status returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/business/connect-status');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /business/onboard-link returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/business/onboard-link');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /categories returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/categories');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /customers returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/customers');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /dashboard/revenue-data returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/dashboard/revenue-data');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /dashboard/stock-alerts returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/dashboard/stock-alerts');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /dashboard/summary-cards returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/dashboard/summary-cards');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /dashboard/trend returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/dashboard/trend');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /expense-categories returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/expense-categories');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /expense-categories/active returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/expense-categories/active');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /expenses returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/expenses');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /payment-methods returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/payment-methods');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /products returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/products');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /purchases returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/purchases');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /purchases-return returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/purchases-return');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /purchases/summary/cards returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/purchases/summary/cards');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /qoutations returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/qoutations');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /qoutations/summary/cards returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/qoutations/summary/cards');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /reports/annual returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/reports/annual');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /reports/customers returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/reports/customers');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /reports/expenses returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/reports/expenses');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /reports/inventory returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/reports/inventory');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /reports/profit-loss returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/reports/profit-loss');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /reports/purchases returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/reports/purchases');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /reports/sales returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/reports/sales');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /reports/sold-stock returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/reports/sold-stock');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /reports/stock-history returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/reports/stock-history');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /reports/tax returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/reports/tax');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /role-permissions returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/role-permissions');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /roles returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/roles');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /roles/me/permission returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/roles/me/permission');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /sales returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/sales');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /sales-return returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/sales-return');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /sales/summary/cards returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/sales/summary/cards');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /stores returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/stores');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /suppliers returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/suppliers');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /transfers returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/transfers');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /units returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/units');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /users/profile returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/users/profile');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });

  it('GET /variations returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('/variations');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });
});

/* Skipped dynamic GET endpoints (require path params):
 * GET ${ENDPOINT.ADJUSTMENTS}/${id} (services/adjustments.ts)
 * GET ${ENDPOINT.AUTH.ROLE_PERMISSION_DETAILS}/${roleId}/permission (services/roles.ts)
 * GET ${ENDPOINT.BUSINESS_USERS}/${id} (services/business-users.ts)
 * GET ${ENDPOINT.PRODUCTS}/${id} (services/products.ts)
 * GET ${ENDPOINT.PURCHASES_RETURN}/${id} (services/purchase-returns.ts)
 * GET ${ENDPOINT.PURCHASES}/${id} (services/purchases.ts)
 * GET ${ENDPOINT.PURCHASES}/${id}/pdf (services/purchases.ts)
 * GET ${ENDPOINT.QUOTATIONS}/${id} (services/quotations.ts)
 * GET ${ENDPOINT.QUOTATIONS}/${id}/pdf (services/quotations.ts)
 * GET ${ENDPOINT.SALES_RETURN}/${id} (services/sale-returns.ts)
 * GET ${ENDPOINT.SALES}/${id} (services/sales.ts)
 * GET ${ENDPOINT.SALES}/${id}/pdf (services/sales.ts)
 * GET ${ENDPOINT.TRANSFERS}/${id} (services/transfers.ts)
 */
