import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { InternetCheck } from "@/utils";
import { Inter } from "next/font/google";
import { Providers } from "./providers"


const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});


export const metadata: Metadata = {
  title: {
    template: "%s | E-POS",
    default: "E-POS",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>

      <body className={`debug-screens ${inter.className}`}>

        <Providers>

          {children}

        </Providers>

        <InternetCheck />

        <Toaster
          position="top-center"
          reverseOrder={false}
        />

      </body>

    </html>
  );
}
