import fs from "fs";
import path from "path";

const ROOT = process.cwd();
const ENDPOINT_FILE = path.join(ROOT, "constants/ENDPOINT.ts");
const SERVICES_DIR = path.join(ROOT, "services");
const API_DIR = path.join(ROOT, "tests/api");

type EndpointCall = {
  method: string;
  path: string;
  source: string;
  dynamic: boolean;
};

function parseEndpointMap(content: string): Record<string, string> {
  const map: Record<string, string> = {};
  const stack: string[] = [];

  for (const line of content.split("\n")) {
    const nestedOpen = line.match(/^\s*([A-Z_][A-Z0-9_]*):\s*\{/);
    if (nestedOpen) {
      stack.push(nestedOpen[1]);
      continue;
    }

    if (/^\s*\},?\s*$/.test(line) && stack.length > 0) {
      stack.pop();
      continue;
    }

    const leaf = line.match(/^\s*([A-Z_][A-Z0-9_]*):\s*['"]([^'"]+)['"]/);
    if (leaf) {
      map[[...stack, leaf[1]].join(".")] = leaf[2];
    }
  }

  return map;
}

function resolveEndpointRef(ref: string, map: Record<string, string>): string | null {
  const key = ref.replace(/^ENDPOINT\./, "");
  return map[key] ?? null;
}

function extractCallsFromLine(
  line: string,
  file: string,
  map: Record<string, string>
): EndpointCall[] {
  const methodMatch = line.match(/client\.(get|post|put|patch|delete)/i);
  if (!methodMatch) return [];

  const method = methodMatch[1].toLowerCase();
  const calls: EndpointCall[] = [];

  const templateMatch = line.match(/`([^`]+)`/);
  if (templateMatch) {
    const template = templateMatch[1];
    if (/\$\{(?!ENDPOINT\.)/.test(template)) {
      calls.push({
        method,
        path: template,
        source: file,
        dynamic: true,
      });
      return calls;
    }

    const resolved = template.replace(
      /\$\{ENDPOINT\.([A-Z0-9_.]+)\}/g,
      (_, key: string) => map[key] ?? `__UNRESOLVED_${key}__`
    );

    if (resolved.includes("__UNRESOLVED_")) {
      return calls;
    }

    calls.push({ method, path: resolved, source: file, dynamic: false });
    return calls;
  }

  const endpointRef = line.match(/ENDPOINT(?:\.[A-Z_][A-Z0-9_]*)+/);
  if (endpointRef) {
    const resolved = resolveEndpointRef(endpointRef[0], map);
    if (resolved) {
      calls.push({ method, path: resolved, source: file, dynamic: false });
    }
  }

  return calls;
}

function scanServices(map: Record<string, string>): EndpointCall[] {
  const files = fs
    .readdirSync(SERVICES_DIR)
    .filter((f) => f.endsWith(".ts") && f !== "index.ts");

  const calls: EndpointCall[] = [];

  for (const file of files) {
    const content = fs.readFileSync(path.join(SERVICES_DIR, file), "utf8");
    for (const line of content.split("\n")) {
      calls.push(...extractCallsFromLine(line, `services/${file}`, map));
    }
  }

  return calls;
}

function dedupeCalls(calls: EndpointCall[]): EndpointCall[] {
  const seen = new Set<string>();
  const result: EndpointCall[] = [];

  for (const call of calls) {
    const key = `${call.method}:${call.path}`;
    if (seen.has(key)) continue;
    seen.add(key);
    result.push(call);
  }

  return result.sort((a, b) =>
    a.path === b.path
      ? a.method.localeCompare(b.method)
      : a.path.localeCompare(b.path)
  );
}

function generateSmokeFile(calls: EndpointCall[]): string {
  const getCalls = calls.filter((c) => c.method === "get" && !c.dynamic);
  const skipped = calls.filter((c) => c.method === "get" && c.dynamic);

  const tests = getCalls
    .map(
      (call) => `  it('GET ${call.path} returns 2xx', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.get('${call.path}');
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });`
    )
    .join("\n\n");

  const skippedComment =
    skipped.length > 0
      ? `\n/* Skipped dynamic GET endpoints (require path params):\n${skipped
          .map((c) => ` * ${c.method.toUpperCase()} ${c.path} (${c.source})`)
          .join("\n")}\n */\n`
      : "";

  return `// AUTO-GENERATED by scripts/generate-api-tests.ts — do not edit manually
import { describe, it, expect, beforeAll } from "vitest";
import { createTestClient } from "../lib/testClient";
import { getAuthHeaders } from "../lib/auth";

describe("API smoke tests (GET)", () => {
  beforeAll(async () => {
    await getAuthHeaders();
  });

${tests}
});
${skippedComment}`;
}

function generateIntegrationFile(calls: EndpointCall[]): string {
  const writeCalls = calls.filter(
    (c) => ["post", "put", "patch", "delete"].includes(c.method)
  );

  const tests = writeCalls
    .map(
      (call) => `  it.skip('${call.method.toUpperCase()} ${call.path} (${call.source})', async () => {
    const client = createTestClient(await getAuthHeaders());
    const response = await client.${call.method}('${call.path}', {});
    expect(response.status).toBeGreaterThanOrEqual(200);
    expect(response.status).toBeLessThan(300);
  });`
    )
    .join("\n\n");

  return `// AUTO-GENERATED by scripts/generate-api-tests.ts — do not edit manually
// Write endpoints are skipped by default to avoid mutating live data.
// Enable individual tests in tests/api/manual/ for safe integration cases.
import { describe, it, expect } from "vitest";
import { createTestClient } from "../lib/testClient";
import { getAuthHeaders } from "../lib/auth";

describe("API integration tests (write endpoints)", () => {
${tests || "  it.skip('no write endpoints found', () => {});"}
});
`;
}

function writeE2ePlaceholder() {
  const e2eDir = path.join(ROOT, "test-reports/html/e2e");
  const indexPath = path.join(e2eDir, "index.html");
  if (fs.existsSync(path.join(e2eDir, "data"))) {
    return;
  }

  fs.mkdirSync(e2eDir, { recursive: true });
  fs.writeFileSync(
    indexPath,
    `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>E2E report not generated yet</title>
  <style>
    body { font-family: system-ui, sans-serif; max-width: 560px; margin: 3rem auto; padding: 0 1rem; line-height: 1.5; }
    code { background: #f4f4f4; padding: 0.15rem 0.4rem; border-radius: 4px; }
    a { color: #2563eb; }
  </style>
</head>
<body>
  <h1>Browser smoke report not available yet</h1>
  <p>E2E tests have not been run. Playwright writes this report only after <code>yarn test:e2e</code>.</p>
  <p>From the project root, run:</p>
  <pre><code>yarn test:e2e</code></pre>
  <p>Then refresh this page (with <code>yarn test:report:serve</code> still running), or open the Playwright viewer:</p>
  <pre><code>npx playwright show-report test-reports/html/e2e</code></pre>
  <p><a href="../">← Back to test reports index</a></p>
</body>
</html>`
  );
}

function writeReportIndex() {
  const pkg = JSON.parse(
    fs.readFileSync(path.join(ROOT, "package.json"), "utf8")
  ) as { name: string };
  const templatePath = path.join(ROOT, "tests/reports/index.template.html");
  const template = fs.readFileSync(templatePath, "utf8");
  const html = template.replace(/\{\{PROJECT\}\}/g, pkg.name);
  const htmlDir = path.join(ROOT, "test-reports/html");
  fs.mkdirSync(path.join(htmlDir, "smoke"), { recursive: true });
  fs.mkdirSync(path.join(htmlDir, "integration"), { recursive: true });
  fs.mkdirSync(path.join(htmlDir, "e2e"), { recursive: true });
  fs.writeFileSync(path.join(htmlDir, "index.html"), html);
  writeE2ePlaceholder();
}

function main() {
  const endpointContent = fs.readFileSync(ENDPOINT_FILE, "utf8");
  const map = parseEndpointMap(endpointContent);
  const calls = dedupeCalls(scanServices(map));

  fs.mkdirSync(API_DIR, { recursive: true });
  fs.mkdirSync(path.join(ROOT, "tests/api/manual"), { recursive: true });
  writeReportIndex();

  const smokePath = path.join(API_DIR, "smoke.generated.ts");
  const integrationPath = path.join(API_DIR, "integration.generated.ts");

  fs.writeFileSync(smokePath, generateSmokeFile(calls));
  fs.writeFileSync(integrationPath, generateIntegrationFile(calls));

  const smokeCount = calls.filter((c) => c.method === "get" && !c.dynamic).length;
  const integrationCount = calls.filter((c) =>
    ["post", "put", "patch", "delete"].includes(c.method)
  ).length;

  console.log(`Generated ${smokePath} (${smokeCount} GET tests)`);
  console.log(`Generated ${integrationPath} (${integrationCount} write tests, skipped)`);
}

main();
